package com.communicatecraft.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Entity class for City.
 * This class represents a city in the database.
 * The @Data annotation is used to automatically generate getters, setters, equals, hashCode and toString methods.
 * The @Entity annotation is used to indicate that this class is a JPA entity.
 * The @Table annotation is used to specify the details of the table that will be used to create the table in the database.
 */
@Data
@Entity
@Table(name = "City")
public class City {
    /**
     * The ID of the city.
     * This field is automatically generated by the database when a city is created.
     * The @Id annotation is used to specify the primary key of the entity.
     * The @GeneratedValue annotation is used to specify how the primary key should be generated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer cityId;

    /**
     * The name of the city.
     * This field cannot be null, empty or blank, and its maximum length is 128 characters.
     * The @Size, @NotNull, @NotBlank and @NotEmpty annotations are used to validate this field.
     * The @Column annotation is used to specify the details of the column that will be used to create the field in the database.
     */
    @Size(max = 128, message = "City name must be less than 129 characters")
    @NotNull(message = "null city name")
    @NotBlank(message = "blank city name")
    @NotEmpty(message = "empty city name")
    @Column(nullable = false, length = 128, unique = true)
    private String cityName;
}